image:
- Visual Studio 2015

stack: python 3

environment:
  PY_DIR: C:\Python36-x64

clone_depth: 3

build: off

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%APPVEYOR_BUILD_FOLDER%\data\lib;%PATH%
  - cmd: set CNC_INSTALL_CNCA0_CNCB0_PORTS="YES"

install:
  - pip install .\emulator\
  - pip install .\python-package
  - .\emulator\brainflow_emulator\com0com\certmgr.exe  /add .\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine root
  - .\emulator\brainflow_emulator\com0com\certmgr.exe /add .\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine trustedpublisher

test_script:
  - python .\emulator\brainflow_emulator\cyton_windows.py python .\tests\python\brainflow_get_data.py
  - cmake_build.cmd

notifications:
  - provider: Email
    to:
      - a1994ndrey@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
