image:
- Visual Studio 2017

stack: python 3

environment:
  PY_DIR: C:\Python36-x64
  AWS_ACCESS_KEY_ID:
    secure: BkEm2UFU7L/eihM1Sg0/F5SPVtyLqHWMBXXM1CialbE=
  AWS_SECRET_ACCESS_KEY:
    secure: gjIjWPDtmovPZ3/Q7Xo/WfUKzZRZGaXi4BRPuukeL6M8YA0+ydmmuEESk9g7DzuC
  PYPI_PASSWORD:
    secure: ZuRCW1W45pqH03Lio54BzQ==
  GITHUB_TOKEN:
    secure: Q0/Pyd8J+EX6/zaOuWATGu2OvRBLz53SYEFejI91VFiPEOJ0KbyZl+2UdYSzniDI

clone_depth: 3

build: off

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;C:\Program Files\Java\jdk1.8.0\bin;%APPVEYOR_BUILD_FOLDER%\installed64\lib;%APPVEYOR_BUILD_FOLDER%\installed32\lib;%PATH%
  - cmd: set CNC_INSTALL_CNCA0_CNCB0_PORTS="YES"
  - cmd: set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: set BRAINFLOW_VERSION=%APPVEYOR_REPO_TAG_NAME%

install:
  # compile brainflow for 32 and 64
  - mkdir %APPVEYOR_BUILD_FOLDER%\build32 && cd %APPVEYOR_BUILD_FOLDER%\build32 && cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=8.1 -DCMAKE_INSTALL_PREFIX=..\installed32\ .. && cmake --build . --target install --config Release > brainflow_build32_stdout.txt
  - mkdir %APPVEYOR_BUILD_FOLDER%\build64 && cd %APPVEYOR_BUILD_FOLDER%\build64 && cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=8.1 -DCMAKE_INSTALL_PREFIX=..\installed64\ .. && cmake --build . --target install --config Release > brainflow_build64_stdout.txt
  # nuget package for csharp
  - nuget install Accord -OutputDirectory ../csharp-package/brainflow/packages && nuget install Accord.Math -OutputDirectory ../csharp-package/brainflow/packages
  # charp build Any CPU
  - cd %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow && msbuild brainflow.sln /p:Configuration=Release /p:Platform="Any CPU"
  # install emulator for cyton
  - pip install %APPVEYOR_BUILD_FOLDER%\emulator\
  - cd %APPVEYOR_BUILD_FOLDER% && %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\com0com\certmgr.exe  /add %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine root
  - cd %APPVEYOR_BUILD_FOLDER% && %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\com0com\certmgr.exe /add %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine trustedpublisher
  # install python package
  - pip install %APPVEYOR_BUILD_FOLDER%\python-package\
  # build cpp
  - mkdir %APPVEYOR_BUILD_FOLDER%\tests\cpp\build && cd %APPVEYOR_BUILD_FOLDER%\tests\cpp\build && cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=8.1 -DCMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%\installed64\ .. && cmake --build . --config Release > cpp_test_build64_stdout.txt
  - mkdir %APPVEYOR_BUILD_FOLDER%\tests\cpp\build32 && cd %APPVEYOR_BUILD_FOLDER%\tests\cpp\build32 && cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=8.1 -DCMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%\installed32\ .. && cmake --build . --config Release > cpp_test_build32_stdout.txt
  # mvn package for java
  - cd %APPVEYOR_BUILD_FOLDER%\java-package\brainflow && mvn package > maven_package_stdout.txt

test_script:
  # tests for cyton
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py python %APPVEYOR_BUILD_FOLDER%\tests\python\brainflow_get_data.py --log --board-id 0 --serial-port
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py python %APPVEYOR_BUILD_FOLDER%\tests\python\brainflow_multiboard_get_data.py --log --board-id 0 --serial-port
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py %APPVEYOR_BUILD_FOLDER%\tests\cpp\build\Release\test_get_data.exe --board-id 0 --serial-port
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py %APPVEYOR_BUILD_FOLDER%\tests\cpp\build32\Release\test_get_data.exe --board-id 0 --serial-port
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow\test\bin\Release\test.exe --board-id 0 --serial-port
  # tests for synthetic
  - python %APPVEYOR_BUILD_FOLDER%\tests\python\brainflow_get_data.py --log --board-id -1
  - echo "stub text to dont start command with special character" && %APPVEYOR_BUILD_FOLDER%\tests\cpp\build\Release\test_get_data.exe --board-id -1
  - cd %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow\test\bin\Release && test.exe --board-id -1
  # tests for cyton daisy
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py python %APPVEYOR_BUILD_FOLDER%\tests\python\brainflow_get_data.py --log --board-id 2 --serial-port
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py %APPVEYOR_BUILD_FOLDER%\tests\cpp\build\Release\test_get_data.exe --board-id 2 --serial-port
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\cyton_windows.py %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow\test\bin\Release\test.exe --board-id 2 --serial-port
  # tests for novaxr
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\novaxr_udp.py python %APPVEYOR_BUILD_FOLDER%\tests\python\brainflow_get_data.py --board-id 3 --ip-address 127.0.0.1 --ip-protocol 1
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\novaxr_udp.py %APPVEYOR_BUILD_FOLDER%\tests\cpp\build\Release\test_get_data.exe --board-id 3 --ip-address 127.0.0.1 --ip-protocol 1
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\novaxr_udp.py %APPVEYOR_BUILD_FOLDER%\tests\cpp\build32\Release\test_get_data.exe --board-id 3 --ip-address 127.0.0.1 --ip-protocol 1
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\novaxr_udp.py %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow\test\bin\Release\test.exe --board-id 3 --ip-address 127.0.0.1 --ip-protocol 1
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\novaxr_tcp.py %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow\test\bin\Release\test.exe --board-id 3 --ip-address 127.0.0.1 --ip-protocol 2
  # tests for wifi shield based boards
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\wifi_shield_emulator.py python %APPVEYOR_BUILD_FOLDER%\tests\python\brainflow_get_data.py --board-id 4 --ip-address 127.0.0.1 --ip-protocol 2 --ip-port 17982
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\wifi_shield_emulator.py %APPVEYOR_BUILD_FOLDER%\tests\cpp\build\Release\test_get_data.exe --board-id 5 --ip-address 127.0.0.1 --ip-protocol 2 --ip-port 17983
  - python %APPVEYOR_BUILD_FOLDER%\emulator\brainflow_emulator\wifi_shield_emulator.py %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow\test\bin\Release\test.exe --board-id 6 --ip-address 127.0.0.1 --ip-protocol 2 --ip-port 17984

deploy_script:
  - python -m pip install wheel > wheel_install.txt
  - python -m pip install twine > twine_install.txt
  - python -m pip install awscli > awscli_install.txt
  # upload to S3 in all cases, we will always be able to download libs
  - aws s3 cp %APPVEYOR_BUILD_FOLDER%\installed32\inc\ s3://brainflow/%APPVEYOR_REPO_COMMIT%/inc --recursive
  - aws s3 cp %APPVEYOR_BUILD_FOLDER%\installed32\lib\ s3://brainflow/%APPVEYOR_REPO_COMMIT%/lib32 --recursive
  - aws s3 cp %APPVEYOR_BUILD_FOLDER%\installed64\lib\ s3://brainflow/%APPVEYOR_REPO_COMMIT%/lib64 --recursive
  # download files from travis using S3 create package and publish it
  - ps: >-
      cd $env:APPVEYOR_BUILD_FOLDER\csharp-package\brainflow\brainflow;
      If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") {
        (gc .\brainflow.nuspec).replace('VERSION_PLACEHOLDER',$env:APPVEYOR_REPO_TAG_NAME) | Out-File -encoding ASCII brainflow.nuspec
      }
      Else {
        (gc .\brainflow.nuspec).replace('VERSION_PLACEHOLDER','1.0.0') | Out-File -encoding ASCII brainflow.nuspec
      }
      nuget pack brainflow.csproj -properties Configuration=Release -IncludeReferencedProjects;
      aws s3 cp %APPVEYOR_BUILD_FOLDER%\csharp-package\brainflow\brainflow s3://brainflow/%APPVEYOR_REPO_COMMIT%/nuget --recursive;

      $lin = $false;
      $osx = $false;
      for ($i=0; $i -lt 30; $i++) {
        # wait 30 minutes or until mac and linux binaries appear in s3
        aws s3 ls s3://brainflow/$env:APPVEYOR_REPO_COMMIT/linux_success;
        $lin = $?;
        aws s3 ls s3://brainflow/$env:APPVEYOR_REPO_COMMIT/osx_success;
        $osx = $?
        if($lin -and $osx) {break}
        # stop waiting if linux or mac tests fail
        aws s3 ls s3://brainflow/$env:APPVEYOR_REPO_COMMIT/linux_failure;
        $lin_fail = $?;
        aws s3 ls s3://brainflow/$env:APPVEYOR_REPO_COMMIT/osx_failure;
        $osx_fail = $?
        if($lin_fail -or $osx_fail) {
          write-output "Skip deployment, travis build failed"
          break
        }
        Start-Sleep -s 60;
        echo "not found"
      }
      If ($lin -and $osx) {
        write-output "Binaries found - running deployment"
        New-Item $env:APPVEYOR_BUILD_FOLDER\linux -itemtype directory
        New-Item $env:APPVEYOR_BUILD_FOLDER\osx -itemtype directory
        aws s3 cp s3://brainflow/$env:APPVEYOR_REPO_COMMIT/linux/ $env:APPVEYOR_BUILD_FOLDER\linux\ --recursive
        ls  $env:APPVEYOR_BUILD_FOLDER\linux
        aws s3 cp s3://brainflow/$env:APPVEYOR_REPO_COMMIT/osx/ $env:APPVEYOR_BUILD_FOLDER\osx\ --recursive
        ls $env:APPVEYOR_BUILD_FOLDER\osx
        cd $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\linux\*" -Destination "$env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\src\main\resources" -Recurse
        Copy-Item "$env:APPVEYOR_BUILD_FOLDER\osx\*" -Destination "$env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\src\main\resources" -Recurse
        ls $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\src\main\resources;
        mvn package > mvn_final_stdout.txt
        #upload .jars to aws
        aws s3 cp %APPVEYOR_BUILD_FOLDER%\java-package\brainflow\target\ s3://brainflow/%APPVEYOR_REPO_COMMIT%/jars --recursive

        If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") {
          Copy-Item "$env:APPVEYOR_BUILD_FOLDER\linux\*" -Destination "$env:APPVEYOR_BUILD_FOLDER\python-package\brainflow\lib" -Recurse
          Copy-Item "$env:APPVEYOR_BUILD_FOLDER\osx\*" -Destination "$env:APPVEYOR_BUILD_FOLDER\python-package\brainflow\lib" -Recurse
          ls $env:APPVEYOR_BUILD_FOLDER\python-package\brainflow\lib
          cd $env:APPVEYOR_BUILD_FOLDER\python-package
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*.whl --user Andrey1994 --password $env:PYPI_PASSWORD
          cd $env:APPVEYOR_BUILD_FOLDER\tools
          .\github-release.exe release --user Andrey1994 --repo brainflow --tag $env:APPVEYOR_REPO_TAG_NAME
          .\github-release.exe upload --user Andrey1994 --repo brainflow --tag $env:APPVEYOR_REPO_TAG_NAME --name brainflow.jar --file $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\target\brainflow.jar
          .\github-release.exe upload --user Andrey1994 --repo brainflow --tag $env:APPVEYOR_REPO_TAG_NAME --name brainflow-jar-with-dependencies.jar --file $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\target\brainflow-jar-with-dependencies.jar
        }
        Else {
          write-output "Skip deployment for non tag"
        }
      }
      Else {
        write-output "Failed to wait for mac and linux libs"
      }

on_finish:
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\build32\brainflow_build32_stdout.txt
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\build64\brainflow_build64_stdout.txt
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\java-package\brainflow\maven_package_stdout.txt

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
