name = "BrainFlow"
uuid = "abd5acf9-0fc9-4730-984d-e27a37823580"
authors = ["Andrey1994 <a1994ndrey@gmail.com>"]
version = "4.7.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
JSON = "0.21.1"
MacroTools = "0.5.6"
Tar = "1.8.0"
julia = "1.3"
