[brainflow]
git-tree-sha1 = "c0ecab47803cd0fa4546e1bd4b15652f3f1c5e61"
lazy = true

    [[brainflow.download]]
    sha256 = "60ca383b5ae3862929bda7f96e06b02056de756e76a6cc606bfa9fc308b88fb3"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.21.0/compiled_libs.tar"
