[brainflow]
git-tree-sha1 = "08e98b4227318e9102bf6ff93586e1a3f645fcd3"
lazy = true

    [[brainflow.download]]
    sha256 = "9e41e26da9c821c7cc43b3e318629d65797ab981b198f35cf9cf7e3e40935cc4"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.20.0/compiled_libs.tar"
